### ISSUE TITLE
Showing just one single image

### ISSUE THREAD

**Issue by dackom** [Luehang/react-native-image-layout#4]
Hello. I am trying to use this library for search results. Sometimes, my search results have just one image. In that case nothing is displayed. Is there possibility to somehow make this work when there is just one image in array, and if possible in one full width column?

**Comment by Luehang** [comment]
Hi,

It does display that one image in the array.  If you are having problems with it, try updating it to the latest version.

```bash
npm install --save react-native-image-layout@latest
```

**Comment by Luehang** [comment]
If you would like to see an example project and experiment with `react-native-image-layout`, follow the steps below.

### 1. Clone the Repo

**Clone** `react-native-image-layout` locally. In a terminal, run:

```bash
$ git clone https://github.com/Luehang/react-native-image-layout.git react-native-image-layout
```

<br/>

### 2. Install and Run

```bash
$ cd react-native-image-layout/example/
```

#### iOS - Mac - Install & Run

	1. check out the code
	2. npm install
    3. react-native link
	4. npm run ios

#### Android - Mac - Install & Run

	1. check out the code
	2. npm install
    3. react-native link
	4. emulator running in separate terminal
	5. npm run android
