### ISSUE TITLE
First time image load so so so slow

### ISSUE THREAD

**Issue by vishu-mangla** [Luehang/react-native-image-layout#5]
images are loading so slowly initially.even if i have 15 images they are opeing so slowly. after first time it loads fast.but first time it takes 10 second for just 15 images.those images are coming from aws.
Aws is fastest even then it taking a lot  of time.
if i open 20 images it take time more than 20. so it is not user friendly.
reason of taking time is it loads all the photo then show all images.  it should use concept of flatlist.
it should load 5-6 images initailly which can be easily slow on screen then then those 6 images and then load other images. it will be more user friendly.
and while swiping images it lags a lot.
please provide a full example using flatlist which will load images fast 1st time and other function feature should be same.
othereise it cant be used in case of loading 50-10 images
thanks in advance

**Comment by Luehang** [comment]
Hi,

I will take your feedback and help improve this package.  Thanks for the input.  Much needed.

This free open source package has not been improved often, and I have not had the time to look into this.  Sooner or later in the future, there will be a lot of improvements and updates you will be seeing.

From,

Lue Hang

**Comment by Luehang** [comment]
Much appreciate if you can help contribute and make a pull request.  Thanks.

**Comment by vishu-mangla** [comment]
surely gonna contribute if i make any additional module.
and thanks a lot for a wonderfully library with a lot of feature.
you can reduce feature because its making library heavy.
Main feature should be just gallery and then open images and change with swipe.
it will be enough and gonna very fast
A suggestion to make it fast is to load total images divide by 4 approx or any other number initailly and then load other  so it will help a lot in saving time.  if you can gave me any idea to do this thing it will be very helpful..  otherwise i have to find alternate because no one gonna wait this long

**Comment by Luehang** [comment]
Contributions can be made by also improving the package with performance and logic improvements.  Loading images in a masonry layout and into a gallery with many interactions like double tap and zoom are both hard to create and to optimize.  And this package does not include any binary linking which will cause it to be heavy.  This package solves many of the image issues you will encounter in iOS and Android.

**Comment by Luehang** [comment]
There are problems with the loading on Android. And there are many factors that comes in play when you are pulling data/images remotely. You need to be more specific. It's also your end that you have to meet. You can't just pull large files and expect that the connection is forgiving and would be fast. And additionally, using a masonry list with a gallery with many interaction has it's pros and cons.

**Comment by Luehang** [comment]
If you're a new developer or beginner, learn to specify an issue and test.  Or make a pull request.

**Comment by vishu-mangla** [comment]
i will keep this in mind. yes i am a new developer . again thanks for your great work
