### ISSUE TITLE
Initial loading of images is slow

### ISSUE THREAD

**Issue by Devrathi** [Luehang/react-native-image-layout#6]
Hey Luehang,

Thanks a lot, the library is very cool, everything is working fine but I'm facing a problem with the load time. It is taking about 20-25 seconds to initially load the images in my app. Can you please suggest me what should I do to improve the load time.

Thanks in advance.
Regards

**Comment by Luehang** [comment]
Hi,

There are problems with the loading on Android.  And there are many factors that comes in play when you are pulling data/images remotely.  You need to be more specific.  It's also your end that you have to meet.  You can't just pull large files and expect that the connection is forgiving and would be fast.  And additionally, using a masonry list with a gallery with many interaction has it's pros and cons.

**Comment by Luehang** [comment]
If you're a new developer or beginner, learn to specify an issue and test.  Or make a pull request.
